const $=id=>document.getElementById(id);const num=id=>Number($(id).value.replace(/,/g,''))||0;const won=n=>Math.round(n||0).toLocaleString('ko-KR')+'원';const pct=n=>(n||0).toFixed(2)+'%';
function moneyInput(e){let r=e.value.replace(/[^0-9]/g,'');e.value=r?Number(r).toLocaleString('ko-KR'):''}document.querySelectorAll('.money').forEach(e=>{e.addEventListener('input',()=>moneyInput(e));moneyInput(e)});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.target).classList.add('active');window.scrollTo({top:document.querySelector('.tabs').offsetTop-8,behavior:'smooth'})});
function annuity(p,r,n){r=r/100/12;return n<=0?0:r===0?p/n:p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1)}
function calcHome(){let p=num('homePrice'),l=num('homeLoan'),c=num('homeCash'),cost=num('homeCost'),need=Math.max(0,p+cost-l),gap=Math.max(0,need-c);$('homeResult').innerHTML=`<div class="big">${gap?'추가로 필요한 현금':'현재 현금으로 충당 가능'}: ${won(gap)}</div><p>총 매입 필요금액: ${won(p+cost)}</p><p>대출금: ${won(l)} · LTV: ${pct(p?l/p*100:0)}</p><p>필요 자기자금: ${won(need)}</p><p>보유 현금: ${won(c)}</p>`}
function calcTax(){let p=num('taxPrice'),rate=p<=600000000?1:p<900000000?(p/100000000*2/3-3):3;rate=Math.max(1,Math.min(3,rate));let acq=p*rate/100,edu=acq*.1,rural=$('taxArea').value==='over85'?p*.002:0,total=acq+edu+rural;$('taxResult').innerHTML=`<div class="big">예상 합계: ${won(total)}</div><p>취득세: ${won(acq)} · 적용세율 ${pct(rate)}</p><p>지방교육세: ${won(edu)}</p><p>농어촌특별세: ${won(rural)}</p><p>※ 일반 1주택 유상취득 참고 계산입니다.</p>`}
function calcJeonse(){let p=num('jeonsePrice'),r=Number($('jeonseRate').value)||0,c=num('jeonseCash'),ir=Number($('jeonseInterestRate').value)||0,l=p*r/100,need=p-l,gap=Math.max(0,need-c);$('jeonseResult').innerHTML=`<div class="big">추가 필요 현금: ${won(gap)}</div><p>계산상 대출금: ${won(l)}</p><p>필요 자기자금: ${won(need)}</p><p>월 단순 이자: ${won(l*ir/100/12)}</p>`}
function calcInterest(){let p=num('interestLoan'),r=Number($('interestRate').value)||0,m=Number($('interestMonths').value)||0,i=p*r/100*m/12;$('interestResult').innerHTML=`<div class="big">기간 이자: ${won(i)}</div><p>월평균 이자: ${won(i/Math.max(1,m))}</p><p>원금: ${won(p)} · 연이율: ${pct(r)} · 기간: ${m}개월</p>`}
function calcPayment(){let p=num('payLoan'),r=Number($('payRate').value)||0,n=(Number($('payYears').value)||0)*12,m=$('payMethod').value,first,last,total;if(m==='equal'){first=annuity(p,r,n);last=first;total=first*n}else{let q=p/n,rm=r/100/12;first=q+p*rm;last=q+q*rm;total=p+rm*p*(n+1)/2}$('paymentResult').innerHTML=`<div class="big">첫 달 상환금: ${won(first)}</div><p>마지막 달 상환금: ${won(last)}</p><p>총 상환액: ${won(total)}</p><p>총 이자: ${won(total-p)}</p>`}
function calcDSR(){let inc=num('dsrIncome'),old=num('dsrExisting'),loan=num('dsrNewLoan'),r=Number($('dsrRate').value)||0,y=Number($('dsrYears').value)||0,s=Number($('dsrStress').value)||0,n=annuity(loan,r,y*12)*12,st=annuity(loan,r+s,y*12)*12;$('dsrResult').innerHTML=`<div class="big">일반 계산 DSR: ${pct(inc?(old+n)/inc*100:0)}</div><p>일반 연 원리금: ${won(old+n)}</p><p>스트레스 금리 ${pct(s)}p 가정 DSR: <strong>${pct(inc?(old+st)/inc*100:0)}</strong></p><p>※ 실제 심사는 대출별 산정방식 및 최신 스트레스 DSR 기준에 따라 달라집니다.</p>`}
function calcDeposit(){let p=num('depPrincipal'),r=Number($('depRate').value)||0,m=Number($('depMonths').value)||0,g=p*r/100*m/12,t=g*.154,n=g-t;$('depositResult').innerHTML=`<div class="big">세후 예상 이자: ${won(n)}</div><p>세전 이자: ${won(g)}</p><p>세금 15.4% 가정: ${won(t)}</p><p>세후 만기금액: ${won(p+n)}</p>`}
function calcSaving(){let a=num('saveMonthly'),r=Number($('saveRate').value)||0,m=Number($('saveMonths').value)||0,g=0;for(let i=1;i<=m;i++)g+=a*(r/100)*(m-i+1)/12;let p=a*m,t=g*.154;$('savingResult').innerHTML=`<div class="big">세후 예상 만기금액: ${won(p+g-t)}</div><p>납입 원금: ${won(p)}</p><p>세전 이자: ${won(g)}</p><p>세후 이자: ${won(g-t)}</p>`}calcHome();
